from typing import Protocol


class EmbeddingPort(Protocol):
    def embed_query(self, text: str) -> list[float]: ...

    def embed_passage(self, text: str) -> list[float]: ...

    def embed_sentences(self, sentences: list[str]) -> list[list[float]]: ...

    def count_tokens(self, text: str) -> int: ...
